spring:
  application:
    name: taskapi
  jpa:
    open-in-view: false
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        use_sql_comments: true
        highlight_sql: true
        auto_quote_keyword: true
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://133.186.241.167:3306/nhn_academy_106?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: nhn_academy_106
    password: oD8vlmwi!
logging:
  level:
    org.hibernate.orm.jdbc.bind: trace
    org.springframework.transaction.interceptor: trace